version: "3.7"

services:
  db:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-cat_breeds}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-inovadora}
      MYSQL_USER: ${MYSQL_USER:-inovadora}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-inovadora}
    healthcheck:
      test: "exit 0"
    ports:
      - 3336:3306

  api: #utilizar para testes de integração
    image: composer.insis.com.br:8083/inovadora-dev/php-cli:7.2-latest
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - .:/home/inovadora/workspace


networks:
  default:
    external:
      name: inovadora
